pipeline:
  install-and-build:
    image: node:10
    pull: true
    commands:
      - npm install
      - npm run build
      - npm run test

  ecr:
    image: foo
    region:
      - eu-west-1
    create_repository: true
    repo: foo/foo
    storage_driver: overlay
    dockerfile: Dockerfile
    tag:
      - latest
      - 1.0.${DRONE_BUILD_NUMBER}
    build_args:
      - BUILD_NUMBER=1.0.${DRONE_BUILD_NUMBER}
      - VCS_REF=${DRONE_COMMIT}
    when:
      branch: master
      event:
        exclude: pull_request

  sandbox:
    image: foo
    pull: true
    endpoint: foo
    template: .foo.yaml
    custom_parameters:
      min_replicas: 1
      max_replicas: 1
      tag: 1.0.${DRONE_BUILD_NUMBER}
    when:
      branch: master
      event:
        exclude: pull_request
